### ISSUE TITLE
if set false ROCKETCHAT_SSL - its looks like is empty)

### ISSUE THREAD

**Issue by Yambr** [cengizmurat/botpress-rocketchat#3]
`for (const variable of variables) {
    const value = process.env[variable];
    if (value) {
      config[variable] = value;
    }
  }`

ROCKETCHAT_SSL = false

 if (value) {  // always false

**Comment by cengizmurat** [comment]
Hello, thank you to point the issue, it just has been fixed in [this commit 2f402aa7072b49849f2fa1ae53bccf10b5b247d2](https://github.com/cengizmurat/botpress-rocketchat/commit/2f402aa7072b49849f2fa1ae53bccf10b5b247d2)

Can you check it ?

**Comment by Yambr** [comment]
thanks!)
