### ISSUE TITLE
[bug] Bot send message for two channels

### ISSUE THREAD

**Issue by Yambr** [cengizmurat/botpress-rocketchat#4]
bot is talking to itself

Steps to reproduce:

1. add bot to public channel
2. create discussion
3. say anything in discussion

see bot talks in public channel) 

this video about it)
https://drive.google.com/file/d/1Cq-om43TFgdspZuqXJ1v7PaMxLeLxr4O/view

**Comment by cengizmurat** [comment]
Thank you @Yambr
