### ISSUE TITLE
Please hide not working buttons after use

### ISSUE THREAD

**Issue by Yambr** [cengizmurat/botpress-rocketchat#7]
bot on the long flow cant understand old buttons

maybe hide or delete messeges from chat with used buttons

https://drive.google.com/file/d/13092jTNdzjRhh3OLc83o5p10IYUOOxvE/view

**Comment by cengizmurat** [comment]
Hello @Yambr 
I am scared that what you are requesting is an evolution of the Rocket.Chat product, and I can not do more about it 🙁

**Comment by Yambr** [comment]
Ok )
